project:
  name: cfn-workshop
  owner: sshvans@amazon.com
  package_lambda: false
  shorten_stack_name: true
  s3_regional_buckets: true
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  main:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      KeyPairName: sshvans
      InstanceType: t2.medium
      SSHLocation: 10.0.0.0/16
      OperatorEMail: operator@example.com
      S3KeyPrefix: cfn-workshop/
      S3BucketRegion: $[taskcat_current_region]
      S3BucketName: $[taskcat_autobucket]
    regions:
    - us-west-2
    s3_bucket: 'tcat-0a820f79e7cf5251aa73ff7df7f4c4a0-us-west-2'
    template: templates/main.template.yaml
  privateWorkload:
    parameters:
      InstanceType: t2.medium
      SSHLocation: 10.0.0.0/16
      KeyName: sshvans
      OperatorEMail: operator@example.com
      PrivateSubnet1ID: subnet-02341e051dbfebfe8
      PrivateSubnet2ID: subnet-07ffbccd1b12d153e
      PublicSubnet1ID: subnet-0347d18d946d1cd52
      PublicSubnet2ID: subnet-0779e818af70c77d7
      VPCID: vpc-01c486f04348833cc
    regions:
    - us-west-2
    s3_bucket: 'tcat-0a820f79e7cf5251aa73ff7df7f4c4a0-us-west-2'
    template: templates/private.workload.template.yaml
  publicWorkload:
    parameters:
      InstanceType: t2.medium
      SSHLocation: 10.0.0.0/16
      KeyName: sshvans
      OperatorEMail: operator@example.com
      PublicSubnet1ID: subnet-0338a41a4d5957f9f
      PublicSubnet2ID: subnet-0ddedd01e75dc95b4
      VPCID: vpc-0f74f3037f78b3fc1
    regions:
    - us-west-2
    s3_bucket: 'tcat-0a820f79e7cf5251aa73ff7df7f4c4a0-us-west-2'
    template: templates/public.workload.template.yaml
  workload:
    parameters:
      SSHLocation: 10.0.0.0/16
      KeyName: sshvans
      OperatorEMail: operator@example.com
    regions:
    - us-west-2
    s3_bucket: ''
    template: templates/workload.template.yaml