AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create an EC2 Instance'

  WorkloadInstanceType:
    AllowedValues:
    - t2.small
    - t2.medium
    - t2.large

Mappings:
  AWSAMIRegionMap:
    AMI:
      AMZNLINUXHVM: amzn-ami-hvm-2018.03.0.20181129-x86_64-gp2
    ap-northeast-1:
      AMZNLINUXHVM: ami-00a5245b4816c38e6
    ap-northeast-2:
      AMZNLINUXHVM: ami-00dc207f8ba6dc919
    ap-south-1:
      AMZNLINUXHVM: ami-0ad42f4f66f6c1cc9
    ap-southeast-1:
      AMZNLINUXHVM: ami-05b3bcf7f311194b3
    ap-southeast-2:
      AMZNLINUXHVM: ami-02fd0b06f06d93dfc
    ca-central-1:
      AMZNLINUXHVM: ami-07423fb63ea0a0930
    eu-central-1:
      AMZNLINUXHVM: ami-0cfbf4f6db41068ac
    eu-west-1:
      AMZNLINUXHVM: ami-08935252a36e25f85
    eu-west-2:
      AMZNLINUXHVM: ami-01419b804382064e4
    sa-east-1:
      AMZNLINUXHVM: ami-05145e0b28ad8e0b2
    us-east-1:
      AMZNLINUXHVM: ami-0080e4c5bc078760e
    us-east-2:
      AMZNLINUXHVM: ami-0cd3dfa4e37921605
    us-west-1:
      AMZNLINUXHVM: ami-0ec6517f6edbf8044
    us-west-2:
      AMZNLINUXHVM: ami-01e24be29428c15b2

Resources:
	EC2Instance:
		Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
			KeyName: !Ref KeyPairName
      ImageId: 


