project:
  name: workshop
  owner: owner@amazon.com
  package_lambda: false
  shorten_stack_name: true
  s3_regional_buckets: true
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  main:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      KeyPairName: KEY-PAIR-NAME
      InstanceType: t2.medium
      SSHLocation: 10.0.0.0/16
      OperatorEMail: operator@example.com
      S3KeyPrefix: workshop/
      S3BucketRegion: $[taskcat_current_region]
      S3BucketName: $[taskcat_autobucket]
    regions:
    - us-west-2
    s3_bucket: ''
    template: templates/main.template.yaml